#!/bin/sh
# Load a bootstrap generated env file and exec the real service command.
# Compose resolves `env_file` before any service runs, so secrets that are
# generated by the bootstrap service have to be sourced at container start.
set -eu

environment_file="$1"
shift

if [ ! -r "$environment_file" ]; then
  echo "with-env: $environment_file is missing or unreadable" >&2
  exit 1
fi

set -a
# shellcheck source=/dev/null
. "$environment_file"
set +a

exec "$@"
